pull_request_rules:
  - name: automatic merge
    conditions:
    - label=automerge
    - "check-success=ci/circleci: test"
    actions:
      queue:
        name: speculative

queue_rules:
  - name: speculative
    queue_conditions:
    - "check-success=ci/circleci: test"
    priority_rules:
    - name: high priority
      conditions:
      - label=hotfix-priority
      priority: high
    speculative_checks: 5

