pull_request_rules:
  - name: automatic merge
    conditions:
    - label=automerge
    - check-success=test
    actions:
      queue:
        name: speculative

queue_rules:
  - name: speculative
    conditions:
    - check-success=test
    speculative_checks: 3

