version: 2.1

orbs:
  gh: circleci/github-cli@2.0

jobs:
  test:
    docker:
     - image: amazon/aws-cli
    steps:
    - checkout
    - run: sleep 300 
    - run: echo "this is the test job"

workflows:
  test:
    jobs:
      - test

